CREATE DATABASE IF NOT EXISTS users;
USE users;

CREATE TABLE IF NOT EXISTS data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    grade INT,
    date_created DATETIME
);

INSERT INTO users.data(grade, date_created) VALUES ('100', '2015-12-20 10:01:00');

CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON users.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;