apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-datav2
spec:
  # minReplicas: 1
  # maxReplicas: 10
  # targetCPUUtilizationPercentage: 2
  selector:
    matchLabels:
      app: enter-data
  template:
    metadata:
      labels:
        app: enter-data
    spec:
      containers:
        - args:
            - sh
            - -c
            - /wait && python3 ./app.py
          env:
            - name: WAIT_HOSTS
              value: mysql-db:3306
            - name: WAIT_HOSTS_TIMEOUT
              value: "300"
            - name: WAIT_HOST_CONNECT_TIMEOUT
              value: "30"
            - name: WAIT_SLEEP_INTERVAL
              value: "30"
          name: enter-data
          image: penpen7531/enter_data:v2
          ports:
            - containerPort: 5000
          # Add any additional configuration needed
          resources: {}
