FROM ubuntu

RUN mkdir -p /home/ubuntu/app

WORKDIR /home/ubuntu/app

COPY app.py ./

COPY base.py ./

COPY templates/ ./

RUN mkdir -p /home/ubuntu/app/templates

RUN cp home.html /home/ubuntu/app/templates

RUN cp invalid.html /home/ubuntu/app/templates

RUN cp submit.html /home/ubuntu/app/templates

RUN apt-get update

RUN apt-get install -y python3

RUN apt-get install -y pip

RUN pip install flask

RUN pip install requests

RUN pip install connexion

RUN pip3 install sqlalchemy

RUN pip3 install mysql-connector-python

RUN pip3 install flask

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait


EXPOSE 5000

EXPOSE 80

EXPOSE 8080